### ISSUE TITLE
Context Menu: Dynamic Placement

### ISSUE THREAD

**Issue by Saifullah-dev** [Saifullah-dev/react-file-manager#46]
### Description:
Currently, the context menu in the File Manager component is statically positioned relative to the cursor, which can cause it to be displayed off-screen or in an awkward position when triggered near the window edges. To enhance the user experience, we need to implement dynamic or auto-placement of the context menu to ensure it is always fully visible and optimally positioned.

### Expected Behavior:
- The context menu should automatically adjust its position based on the available screen space.
- When the context menu is triggered near the edge of the window (top, bottom, left, or right), it should reposition itself to remain fully visible.
- The repositioning should be smooth and seamless.

### Steps to Reproduce:
1. Open the File Manager component.
2. Right-click near the edges of the window.
3. Observe the current placement of the context menu.

### Proposed Solution:
- Implement a dynamic positioning algorithm that calculates the optimal position for the context menu based on the cursor’s location and the window boundaries.
- Integrate this feature into the existing context menu logic within the File Manager component.

### Todos:
- [x] Implement the dynamic positioning logic within the File Manager component.
- [x] Ensure the context menu remains fully visible regardless of where it's triggered.
- [x] Test the implementation across various screen sizes and browser window dimensions.

**Comment by Saifullah-dev** [comment]
[e.clientX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX) gives the cursor position relative the window inner width. Hence, to calculate distance from cursor click to left end of our container, we'll subtract clientX with container's left position (files Container):

```javascript
const container = filesViewRef.current;
const containerRect = container.getBoundingClientRect();

const leftToCursor = clickX - containerRect.left;
```
## Left Calculation from cursor sample diagram:

![Image](https://github.com/user-attachments/assets/227ab413-ead9-48f3-9274-1e89731b1940)

**Comment by Saifullah-dev** [comment]
### Positioning Formulae:



![Image](https://github.com/user-attachments/assets/ed2a514b-8290-4417-9faa-0e926d83d3b9)

**Comment by Saifullah-dev** [comment]
## Final Algo:



![Image](https://github.com/user-attachments/assets/e7506493-acf3-432e-b8dc-8d26f5d95cb6)
