### ISSUE TITLE
Feature: List Layout

### ISSUE THREAD

**Issue by Saifullah-dev** [Saifullah-dev/react-file-manager#50]
### Todos:
- [x] Within the Toolbar, add an option to toggle between Grid and List layouts.
- [x] The List layout should also display **Modified (Date Modified)** and **Size** in columns along with the file name.
- [x] Provide **onLayoutChange** callback prop as well that provides new selected layout as a parameter.
- [x] Adust the inline folder creation and renaming feature accordingly.
