### ISSUE TITLE
API Documentation (Swagger)

### ISSUE THREAD

**Issue by Saifullah-dev** [Saifullah-dev/react-file-manager#73]
**Todos:**
- [ ] Create API documentation using [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express).
- [ ] Using [swagger-autogen](https://www.npmjs.com/package/swagger-autogen), generate boilerplate swagger-output.json of available API routes.
- [ ] Add detailed description, expected response etc. on top of that boilerplate.
